### ISSUE TITLE
Update Wordpress

### ISSUE THREAD

**Issue by vai21** [PhilippHeuer/wordpress-heroku#17]
### Description of your issue
I want to update my wordpress in heroku to 4.8.3 but it can't automatically update, thanks btw I can have wordpress in heroku now, great job!

### Steps to Reproduce
open the wordpress dashboard

### Other Information 
Git Commit/Version: 
master

**Comment by PhilippHeuer** [comment]
The wiki has an example on how to update wordpress ->
https://github.com/PhilippHeuer/wordpress-heroku/wiki/WordPress---Update

You can't update it over the dashboard since you can't write to the filesystem - therefore you have to redeploy it.

This only works if you used the `Deployment - Heroku - Manual` Method from https://github.com/PhilippHeuer/wordpress-heroku/wiki/Deployment to deploy your wordpress instance.
