### ISSUE TITLE
default account?

### ISSUE THREAD

**Issue by marty331** [PhilippHeuer/wordpress-heroku#4]
I created the app very easily however I have no idea what the default login and password are for the actual site.   Is there  a default?  If so, what is it?  If not, how do I create an admin account?

**Comment by PhilippHeuer** [comment]
This means you used the heroku deploy button right?

As long as you don't fill the field `HEROKU_APP_NAME` you will get redirected to the setup page right after your deploy. You can create your admin account there.

That's why `Only for automated deploys, please don't enter anything!` stands under the `HEROKU_APP_NAME` textbox. My guess is you entered something there?

You will have to remove your app again. If that field is filled a random admin user will be generated, since this is only used for the testing environment.

**Comment by marty331** [comment]
Yes, you got it exactly right, I filled in the HEROKU_APP_NAME!  D'oh!


Thank you,

Marty Ballard
Pillar Consulting LLC
214-228-5632
marty@pillar-soft.com
w <http://google.com/+MartyBallard>ww.pillar-soft.com
