### ISSUE TITLE
Local execution and custom templates / plugins

### ISSUE THREAD

**Issue by gmmcal** [PhilippHeuer/wordpress-heroku#5]
I've been trying to setup an already running wordpress project to run with this configuration, but I'm having 2 issues that occur prior to deploy

- How can I run the project locally
- How can I test locally with my custom plugins and themes that are not on some public repository?

My current setup is a Vagrant VM provisioned with PuPHPet.

**Comment by gmmcal** [comment]
I've found a way to start a local server with `wp server` command from wp-cli. But custom themes are not loading properly, probably because they are located on web/app and the server starts on web/wp... any tips on that?

**Comment by PhilippHeuer** [comment]
One method is indeed wp cli, but i will also add a Dockerfile in the next few days.

I just noticed that the path in `wp-cli.yml` i set to `web/wp` - while it should point to `web`.

You can start the local server with `wp server --docroot=web` for now to override it. Thanks for reporting this mistake - this should also fix your theme problem since the files in app are loaded by `web/wp-config.php`.

**Comment by gmmcal** [comment]
Nice @PhilippHeuer. I've just done a quick test changing the `wp-cli.yml` and looks like it fixed the custom template... I'll do more testings using custom plugins on the next few days and get back here if I find something wrong again.

PS: I haven't deployed the changes I've done to production yet... I hope it works without problems 😄
