### ISSUE TITLE
Installing plugin wiki

### ISSUE THREAD

**Issue by fanky10** [PhilippHeuer/wordpress-heroku#9]
### Wiki documentation 
On wiki: https://github.com/PhilippHeuer/wordpress-heroku/wiki/WordPress---Plugins---Themes

There is a step missing on installing a plugin locally. The final step to update composer dependencies:

```
composer update
git push heroku <custom-branch>:master
```

**Comment by PhilippHeuer** [comment]
Hey, thanks for your notice.

I updated the WIKI.

**Comment by abdurrahman** [comment]
Hi Philipp,
Firstly, i'd like say thanks for this repo. This is my first clutch on Heroku. :rocket: 

I realized plugin/theme not installing in remote when we push only compose.json. I guess we need to add composer.lock file too. Because it changed after `composer update`. Maybe there is an option in Heroku to execute this command.

```shell
composer update
git add composer.json composer.lock
git commit -m "Added a custom plugin"
git push heroku master
```

I just want to share this without opening a new issue.

Abdurrahman
